In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3]

In [3]:
type(23)

int

In [4]:
type(np.array(lista))

numpy.ndarray

In [5]:
arr = np.array(lista)

In [6]:
arr

array([1, 2, 3])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
np.linspace(0, 11, 11)

array([  0. ,   1.1,   2.2,   3.3,   4.4,   5.5,   6.6,   7.7,   8.8,
         9.9,  11. ])

In [19]:
np.random.randint(0,10, (3,3))

array([[5, 9, 9],
       [8, 0, 3],
       [4, 7, 6]])

In [21]:
np.random.normal(1, 3)

0.4515316297881997

In [24]:
np.random.seed(101)
rans = np.random.randint(0, 100, 10)

In [25]:
rans

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [26]:
rans.max()

95

In [27]:
rans.min()

9

In [29]:
rans.base

In [30]:
rans

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [31]:
rans.mean()

60.799999999999997

In [32]:
rans.argmax()

0

In [38]:
rans

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [34]:
rans.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [35]:
mat = np.arange(0, 100).reshape(10, 10)

In [36]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
mat[4,3]

43

In [39]:
mat[:, 0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
mat[5, :]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [41]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [43]:
filter = mat > 50

In [44]:
mat[filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [45]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])