In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'1.3.0'

In [10]:
hello = tf.constant("Machine Learning")

In [11]:
print(hello)

Tensor("Const_2:0", shape=(), dtype=string)


In [12]:
with tf.Session() as sess:
    result = sess.run(hello)

In [13]:
result

b'Machine Learning'

In [16]:
a = tf.constant(10)

In [17]:
b = tf.constant(20)

In [19]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [20]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [21]:
result

30

<h1>Operations - Matrix</h1>

In [22]:
const = tf.constant(10)

In [23]:
fill_mat = tf.fill((4,4), 10)

In [24]:
fill_mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [26]:
zeros = tf.zeros((4,4))

In [27]:
ones = tf.ones((4,4))

In [29]:
rand = tf.random_normal((4,4), mean=0, stddev=1.0)

In [30]:
randu = tf.random_uniform((4,4), minval=0, maxval=1)

In [31]:
randu

<tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>

In [32]:
lista = [ const, fill_mat, zeros, ones, rand, randu ]

<h3>Interactive Session</h3>
<p>faster way to implement with Session, only use in notebooks like this one</p>

In [35]:
sess = tf.InteractiveSession()

In [37]:
for x in lista:
    print(sess.run(x), '\n') # === x.eval()
    

10 

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] 

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]] 

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]] 

[[-0.04944095 -1.38852859 -0.19774902  0.50460923]
 [-2.42887497  0.07677804  0.27654836 -0.72749835]
 [-1.56140316 -0.88631183 -0.22597806 -0.67913175]
 [ 0.77668935 -0.20967892 -0.44774574 -1.62355995]] 

[[ 0.43599463  0.45343089  0.71078277  0.18953514]
 [ 0.0873189   0.22350991  0.78808081  0.74839759]
 [ 0.89959717  0.84354973  0.89129519  0.16616023]
 [ 0.75995338  0.16500556  0.52242184  0.63859224]] 



<h3>Matrix Multiplication</h3>

In [38]:
a = tf.constant([ [1,2],
                    [3,4]])

In [42]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [43]:
b = tf.constant([ [10],
                    [100]])

In [44]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [45]:
result = tf.matmul(a,b)

In [46]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [47]:
result.eval()

array([[210],
       [430]], dtype=int32)

<h1>Graphs</h1>

<p>In TensorFlow each node is an operation with possible inputs that can supply some output</p>

In [48]:
node1 = tf.constant(1)

In [49]:
node2 = tf.constant(2)

In [51]:
node3 = node1 + node2

In [52]:
with tf.Session() as sess:
    result = sess.run(node3)

In [53]:
result

3

In [54]:
node3

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [55]:
print( tf.get_default_graph() )

In [56]:
g = tf.Graph()

In [59]:
g

In [63]:
print(g is tf.get_default_graph())

False


In [64]:
with g.as_default():
    print(g is tf.get_default_graph())

True
